### places where the most important data is
volumes:
  slurm_jobdir:
  var_log_insaflu:
  var_log_slurm:
  var_lib_mysql:
  insaflu-software:
  tmp_insaflu:
  mlflow_data:
  mlflow_artifacts:

### this is necessary to set an ip to SGE in insaflu
networks:
  insaflu_ubuntu_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

  slurm-network:
    driver: bridge

services:
  # DB for Insaflu
  # test database - psql -U flu_user -W -h localhost -d insaflu_db
  db_insaflu:
    build: components/postgres_postgis/.
    restart: always
    container_name: postgres
    hostname: db_insaflu
    volumes:
      - ${BASE_PATH_DATA}/postgres/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "flu_user"
      POSTGRES_PASSWORD: "flu_user_pass"
      POSTGRES_DB: "insaflu_db"
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    networks:
      insaflu_ubuntu_net:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "flu_user", "-d", "insaflu_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  # responsible to manage the Slurm cluster
  officer:
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: "${TIMEZONE}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f deck-chores >/dev/null || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mysql:
    image: mariadb:12.3.2
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurm-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  slurmdbd:
    image: slurm-runtime:${SLURM_TAG:-25.05.3}
    build:
      context: components/slurm_master/.
      args:
        SLURM_TAG: ${SLURM_TAG:-25.05.3}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - ./components/slurm_master/configs/slurm:/run/secrets/slurm:ro
      - ./components/slurm_master/configs/slurmdbd/slurmdbd.conf:/run/secrets/slurmdbd.conf:ro
      - ./components/slurm_master/configs/munge/munge.key:/run/secrets/munge.key:ro
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      db_insaflu:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - slurm-network
    healthcheck:
      test: ["CMD-SHELL", "pidof slurmdbd"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  slurmctld:
    image: slurm-runtime:${SLURM_TAG:-25.05.3}
    build:
      context: components/slurm_master/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - ./components/slurm_master/configs/slurm:/run/secrets/slurm:ro
      - ./components/slurm_master/configs/munge/munge.key:/run/secrets/munge.key:ro
      - slurm_jobdir:/data:rw
      - var_log_slurm:/var/log/slurm:rw
    expose:
      - "6817"
    depends_on:
      slurmdbd:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - slurm-network
    healthcheck:
      test: ["CMD-SHELL", "scontrol ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s


  c1:
    image: slurm-docker-nodes:${IMAGE_TAG:-25.05.3}
    build:
      context: components/slurm_nodes/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmd", "-D"]
    working_dir: /data
    hostname: c1
    container_name: c1
    privileged: true
    volumes:
      - ./components/slurm_master/configs/slurm:/run/secrets/slurm:ro
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./components/slurm_master/configs/munge/munge.key:/run/secrets/munge.key:ro
      - ${BASE_PATH_DATA}/insaflu/data/all_data:/insaflu_web/INSaFLU/media
      - ${BASE_PATH_DATA}/insaflu/data/static:/insaflu_web/INSaFLU/static_all
      - insaflu-software:/software
      - ${BASE_PATH_DATA}/televir:/opt/televir
      - var_log_insaflu:/var/log/insaFlu
      - tmp_insaflu:/tmp/insaFlu
      - ${BASE_PATH_DATA}/insaflu/env:/insaflu_web/INSaFLU/env
    expose:
      - "6818"
    depends_on:
      slurmctld:
        condition: service_started
      db_insaflu:
        condition: service_healthy
      officer:
        condition: service_healthy
    networks:
      slurm-network:
      insaflu_ubuntu_net:
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x slurmd >/dev/null"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s


  c2:
    image: slurm-docker-nodes:${IMAGE_TAG:-25.05.3}
    build:
      context: components/slurm_nodes/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmd", "-D"]
    working_dir: /data
    hostname: c2
    container_name: c2
    privileged: true
    volumes:
      - ./components/slurm_master/configs/slurm:/run/secrets/slurm:ro
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./components/slurm_master/configs/munge/munge.key:/run/secrets/munge.key:ro
      - ${BASE_PATH_DATA}/insaflu/data/all_data:/insaflu_web/INSaFLU/media
      - ${BASE_PATH_DATA}/insaflu/data/static:/insaflu_web/INSaFLU/static_all
      - insaflu-software:/software
      - ${BASE_PATH_DATA}/televir:/opt/televir
      - var_log_insaflu:/var/log/insaFlu
      - tmp_insaflu:/tmp/insaFlu
      - ${BASE_PATH_DATA}/insaflu/env:/insaflu_web/INSaFLU/env
    expose:
      - "6818"
    depends_on:
      slurmctld:
        condition: service_started
      db_insaflu:
        condition: service_healthy
      officer:
        condition: service_healthy
    networks:
      slurm-network:
      insaflu_ubuntu_net:
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x slurmd >/dev/null"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s


  # insaflu
  # password and database login are defined in components/insaflu/configs/insaflu.env
  insaflu-ubuntu:
    build:
      context: components/insaflu-ubuntu/.
      args:
        SLURM_TAG: ${SLURM_TAG}
        APP_USER: ${APP_USER}
    container_name: insaflu-ubuntu
    image: ${USERNAME_IMAGE}:${IMAGE}
    hostname: insaflu
    restart: "on-failure"
    volumes:
      - ${BASE_PATH_DATA}/televir:/opt/televir
      - ${BASE_PATH_DATA}/insaflu/data/all_data:/insaflu_web/INSaFLU/media
      - ${BASE_PATH_DATA}/insaflu/data/static:/insaflu_web/INSaFLU/static_all
      - ${BASE_PATH_DATA}/insaflu/env:/insaflu_web/INSaFLU/env
      - ${BASE_PATH_DATA}/insaflu/log/httpd:/var/log/httpd
      - insaflu-software:/software
      - slurm_jobdir:/data
      - ./components/slurm_master/configs/slurm:/run/secrets/slurm:ro
      - ./components/slurm_master/configs/munge/munge.key:/run/secrets/munge.key:ro
      - var_log_insaflu:/var/log/insaFlu
      - tmp_insaflu:/tmp/insaFlu
    labels:
      deck-chores.update-pangolin.command: sh -c "/software/update_pangolin.sh"
      # weekly, daily, hourly, every minute and every second.
      deck-chores.update-pangolin.interval: hourly
    depends_on:
      db_insaflu:
        condition: service_healthy
      officer:
        condition: service_healthy
      slurmctld:
        condition: service_started
      c1:
        condition: service_started
      c2:
        condition: service_started
    environment:
      - SGE_ROOT=/opt/sge
    ports:
      - "${APP_PORT}:80"
    tty: true
    stdin_open: true
    networks:
      slurm-network:
      insaflu_ubuntu_net:
    command: ["init_all"]


  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    container_name: mlflow-server

    ports:
      - "5000:5000"

    volumes:
      - mlflow_data:/mlflow
      - mlflow_artifacts:/mlartifacts

    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri sqlite:////mlflow/mlflow.db
        --default-artifact-root file:///mlartifacts
        --no-serve-artifacts
        --allowed-hosts "*"
        --cors-allowed-origins "*"

  ml_app:
    build: components/ml_api/.
    container_name: insaflu-ml-app
    hostname: ml_app

    ports:
      - "8000:8000"

    depends_on:
      - mlflow

    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT=INSaFLU_ML_API

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - mlflow_artifacts:/mlartifacts
