ClusterName=linux
AuthType=auth/munge
SlurmUser=slurm
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
# Client does NOT define nodes or partitions
SlurmctldHost=slurmctld
SlurmctldPort=6817
SlurmdPort=6818
# Client does NOT define nodes or partitions

# include /etc/slurm/slurm.conf.d/*.conf
