ClusterName=linux
AuthType=auth/munge
SlurmUser=slurm
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
# Client does NOT define nodes or partitions
SlurmctldHost=slurmctld
SlurmctldPort=6817
SlurmdPort=6818
# ACCOUNTING
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageUser=slurm
AccountingStorageHost=slurmdbd
AccountingStoragePort=6819
# include /etc/slurm/slurm.conf.d/*.conf
