ClusterName=linux
AuthType=auth/munge
SlurmUser=slurm
# Client does NOT define nodes or partitions
SlurmctldHost=slurmctld
SlurmctldPort=6817
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
#FastSchedule=1
#include /etc/slurm/slurm.conf.d/*.conf
#
# COMPUTE NODES - Dynamic configuration
# Nodes will be automatically registered by the node management service
# Initial placeholder for dynamic nodes
# Always-on node
NodeName=c[1-2] CPUs=8 RealMemory=4000 State=UNKNOWN

DefMemPerCPU=1024  
# PARTITIONS
PartitionName=normal Default=yes Nodes=c[1-2] Priority=50 DefMemPerCPU=500 Shared=NO MaxTime=5-00:00:00 DefaultTime=5-00:00:00 State=UP

